# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: R-CMD-check

env:
  DUCKDB_R_REPO: 'duckdb/duckdb-r'
  TARGET_REF: 'main'
  SRC_DIR: 'duckdb-r'
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: 'oldrel-1'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - name: move code to /duckdb
        shell: bash
        run: mkdir duckdb && mv * duckdb/

      - uses: actions/checkout@v3
        with:
          repository:  ${{ env.DUCKDB_R_REPO }}
          path: ${{ env.SRC_DIR }}

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          working-directory: ${{ env.SRC_DIR }}
          extra-packages: any::rcmdcheck
          needs: check

      - name: update vendors
        shell: bash
        working-directory: ${{ env.SRC_DIR }}
        run: ./vendor.sh

      - name: Run R CMD BUILD & CHECK
        shell: bash
        working-directory: ${{ env.SRC_DIR }}
        run: R CMD BUILD . && R CMD CHECK duckdb_*

      - name: check import
        shell: bash
        working-directory: ${{ env.SRC_DIR }}
        run: R -q -e "library(duckdb)"