name: Stress_Samples
on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches:
      - '**'
      - '!main'
      - '!feature'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

jobs:
  build-versions-create-samples:
    name: Release Assertions
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest ]
    runs-on: ${{ matrix.os }}
    env:
      CC: gcc-10
      CXX: g++-10
      GEN: ninja
      BUILD_JEMALLOC: 1
      CORE_EXTENSIONS: "icu;tpch;tpcds;fts;json;inet"
      DISABLE_SANITIZER: 1
      CRASH_ON_ASSERT: 1
      RUN_SLOW_VERIFIERS: 1

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install
        shell: bash
        run: brew install duckdb

      - name: Setup Ccache
        uses: hendrikmuhs/ccache-action@main
        with:
          key: ${{ github.job }}
          save: ${{ env.CCACHE_SAVE }}

#      - name: Build
#        shell: bash
#        run: UNSAFE_NUMERIC_CAST=1 make relassert

      - name: Create sample file
        shell: bash
        run: |
          duckdb -c "create table tbl1 as select * from range(10000000); create table t2 as select * from t1; copy (select * from duckdb_table_sample('t2') to '${{ matrix.platform }}_sample.csv' (FORMAT CSV)"

      - name: upload sample file
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}_sample.csv
          path: ${{ matrix.platform }}_sample.csv

  verify-samples-are-the-same:
    name: verify-samples-are-the-same
    needs: build-versions-create-samples
    runs-on: macos-latest
    steps:
      - uses: actions/download-artifact@v4

      - name: check all samples are the same
        shell: bash
        run: |
          diff *.csv > diffs.txt

      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
